task:
  matrix:
    - name: sequoia
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sequoia
    - name: sonoma
      macos_instance:
        image: ghcr.io/cirruslabs/macos-runner:sonoma
  setup_script:
    - brew install chezscheme
  test_script:
    - chez --script examples/ifaces.ss
    - chez --script examples/network.ss
